# Generated by Django 2.2.5 on 2019-09-25 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Projects',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateField()),
                ('Location', models.IntegerField(choices=[(1, 'INSIDE'), (2, 'OUTSIDE'), (3, 'OTHER')], default=1)),
                ('details', models.TextField(blank=True, null=True)),
                ('working_hour', models.PositiveIntegerField(help_text='eg: 8 Hours')),
                ('is_cod', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='works_of_user', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='works_of_project', to='works.Project')),
            ],
            options={
                'verbose_name_plural': 'Works',
                'ordering': ('-pk',),
            },
        ),
    ]
