# Generated by Django 2.2.5 on 2019-09-25 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='works',
            old_name='Location',
            new_name='location',
        ),
    ]
